const interestingFeatures = {
    765: ["gep_internal", "game_info"],
    4688: ["gep_internal", "game_info", "match_info"],
    5426: [
        "gep_internal",
        "summoner_info",
        "gameMode",
        "teams",
        "gold",
        "minions",
        "matchState",
        "level",
        "kill",
        "death",
        "respawn",
        "assist",
        "abilities",
        "counters",
        "match_info",
        "live_client_data",
        "heal",
        "damage",
        "jungle_camps",
        "team_frames",
        "chat",
        "announcer",
        "panel_location",
    ],
    6350: ["gep_internal", "match_info"],
    7212: ["gep_internal", "kill", "death", "match_info", "me", "game_info"],
    7314: [
        "gep_internal",
        "party",
        "roster",
        "match_info",
        "game_state_changed",
        "match_ended",
        "kill",
        "assist",
        "death",
        "cs",
        "hero_attributes_skilled",
        "hero_ability_skilled",
        "hero_ability_used",
        "me",
        "game",
        "match_state_changed",
        "clock_time_changed",
        "game_state",
        "damage",
    ],
    8032: ["gep_internal", "game_info", "match_info", "counters", "mods"],
    8954: ["gep_internal", "game_info", "match_info"],
    9898: [
        "gep_internal",
        "collection",
        "scene_state",
        "decks",
        "match",
        "match_info",
        "arena",
    ],
    10798: [
        "gep_internal",
        "stats",
        "teamGoal",
        "opposingTeamGoal",
        "match",
        "roster",
        "me",
        "match_info",
        "death",
        "game_info",
        "training",
    ],
    10826: [
        "gep_internal",
        "game_info",
        "match",
        "roster",
        "kill",
        "death",
        "match_info",
        "me",
        "defuser",
    ],
    10844: [
        "gep_internal",
        "match_info",
        "kill",
        "death",
        "assist",
        "game_info",
        "roster",
    ],
    10902: [
        "gep_internal",
        "summoner_info",
        "game_flow",
        "champ_select",
        "lobby_info",
        "end_game",
        "lcu_info",
        "game_info",
    ],
    10906: [
        "gep_internal",
        "kill",
        "match",
        "rank",
        "death",
        "location",
        "me",
        "team",
        "phase",
        "map",
        "roster",
        "revived",
        "killer",
        "counters",
        "match_info",
        "victimName",
    ],
    // League of legends: Swarm
    // special game ID, see https://dev.overwolf.com/ow-native/live-game-data-gep/supported-games/league-of-legends-swarm/
    13956: [
        "gep_internal",
        "match",
        "death",
        "abilities",
        "minions",
        "chat",
        "teams",
        "counters",
        "team_frames",
        "respawn",
        "match_info",
        "matchState",
        "damage",
        "summoner_info",
        "live_client_data",
    ],
    21216: [
        "gep_internal",
        "items",
        "kill",
        "match_info",
        "rank",
        "me",
        "phase",
        "location",
        "team",
        "killed",
        "killer",
        "revived",
        "death",
        "counters",
        "match",
        "map",
        "game_info",
    ],
    21308: ["gep_internal", "game_info", "match_info"],
    21404: [
        "gep_internal",
        "game_info",
        "match_info",
        "player",
        "location",
        "match",
        "feed",
        "connection",
        "kill",
        "death",
        "portal",
    ],
    21556: [
        "gep_internal",
        "match",
        "summoner_info",
        "matchState",
        "live_client_data",
        "match_info",
        "augments",
        "damage",
        "heal",
        "teams",
    ],
    21566: [
        "gep_internal",
        "match_state",
        "kill",
        "death",
        "me",
        "team",
        "revive",
        "rank",
        "location",
        "roster",
        "match_summary",
        "kill_feed",
        "damage",
        "inventory",
        "match_info",
        "game_info",
        "localization",
    ],
    21570: [
        "gep_internal",
        "match_info",
        "me",
        "roster",
        "store",
        "board",
        "bench",
        "carousel",
        "live_client_data",
    ],
    21620: ["gep_internal", "game_client_data", "match_info"],
    21634: ["gep_internal", "match_info", "game_info"],
    21640: ["gep_internal", "game_info", "me", "kill", "death", "match_info"],
    21656: ["gep_internal", "game_info", "match_info"],
    21816: ["gep_internal", "game_info"],
    21848: ["gep_internal", "game_info", "match_info"],
    21854: [
        "gep_internal",
        "match_info",
        "game_info",
        "kill",
        "death",
        "assist",
    ],
    21864: ["gep_internal", "game_info", "match_info", "location"],
    21876: ["gep_internal", "match_info", "game_info", "me", "kill", "death"],
    22088: ["gep_internal", "game_info", "match_info", "location"],
    22176: ["gep_internal", "match_info", "game_info"],
    22328: ["gep_internal", "match_info", "game_info"],
    22584: ["gep_internal", "match_info"],
    22638: ["gep_internal", "match_info", "location"],
    22700: ["gep_internal", "match_info", "game_info", "location", "me"],
    22730: ["gep_internal", "match_info", "live_data"],
    22804: ["gep_internal", "game_info", "match_info"],
    22848: [
        "gep_internal",
        "summoner_info",
        "gameMode",
        "teams",
        "gold",
        "minions",
        "matchState",
        "level",
        "kill",
        "death",
        "respawn",
        "assist",
        "abilities",
        "counters",
        "match_info",
        "live_client_data",
        "heal",
        "damage",
        "jungle_camps",
        "team_frames",
        "chat",
        "announcer",
    ],
    22894: ["gep_internal", "match_info", "game_info"],
    23424: ["gep_internal", "match_info", "game_info"],
    23478: ["gep_internal", "game_info", "match_info"],
    23522: ["gep_internal", "game_info", "match_info"],
    23930: ["gep_internal", "game_info", "match_info"],
    23944: ["gep_internal", "game_info", "match_info", "location"],
    24000: ["gep_internal", "game_info", "match_info"],
    24110: ["gep_internal", "game_info", "match_info"],
    24300: ["gep_internal", "game_info", "match_info"],
    24346: ["gep_internal", "match_info", "game_info"],
    24482: ["gep_internal", "game_info", "match_info"],
    24504: ["gep_internal", "game_info", "match_info"],
    24542: ["gep_internal", "game_info", "match_info"],
    24548: ["gep_internal", "match_info", "game_info"],
    24886: ["gep_internal", "me", "match_info", "death", "kill", "game_info"],
    24890: ["gep_internal", "match_info", "game_info"],
    25446: ["gep_internal", "game_info", "match_info"],
    25448: ["gep_internal", "match_info", "game_info"],
    25610: ["gep_internal", "game_info", "match_info", "location"],
    25884: ["gep_internal", "match_info", "game_info"],
    25918: ["gep_internal", "match_info", "game_info"],
    26092: ["gep_internal", "game_info", "match_info"],
    26120: ["gep_internal", "game_info", "match_info"],
    26840: ["gep_internal", "game_info", "match_info"],
    // League of Legends: Arena PBE (Public Beta Environment)
    // special game ID, see https://dev.overwolf.com/ow-native/live-game-data-gep/supported-games/league-of-legends-arena/#game-events-status
    215561: [
        "gep_internal",
        "live_client_data",
        "matchState",
        "summoner_info",
        "match",
        "match_info",
        "augments",
        "damage",
        "heal",
        "teams",
    ],
    // Teamfight Tactics PBE (Public Beta Environment)
    // special game ID, see https://dev.overwolf.com/ow-native/live-game-data-gep/supported-games/teamfight-tactics/
    215701: [
        "gep_internal",
        "live_client_data",
        "carousel",
        "bench",
        "board",
        "store",
        "roster",
        "me",
        "match_info",
        "augments",
    ],
    234241: ["gep_internal", "game_info", "match_info"],
}

const windowNames = {
    desktop: "desktop",
}

export { interestingFeatures, windowNames }
