const interestingFeatures = {
    765: [
        "gep_internal",
        "game_info",
        "addons",
    ],
    5426: [
        "gep_internal",
        "summoner_info",
        "gameMode",
        "teams",
        "gold",
        "minions",
        "matchState",
        "level",
        "kill",
        "death",
        "respawn",
        "assist",
        "abilities",
        "counters",
        "match_info",
        "live_client_data",
        "heal",
        "damage",
        "jungle_camps",
        "team_frames",
        "chat",
        "announcer",
    ],
    5855: [
        "gep_internal",
        "match_info",
    ],
    6350: [
        "gep_internal",
        "match_info",
    ],
    6365: [
        "gep_internal",
        "kill",
        "death",
        "game_info",
        "match_info",
    ],
    7212: [
        "gep_internal",
        "kill",
        "death",
        "match_info",
        "me",
        "game_info",
    ],
    7314: [
        "gep_internal",
        "party",
        "roster",
        "match_info",
        "game_state_changed",
        "match_ended",
        "kill",
        "assist",
        "death",
        "cs",
        "hero_attributes_skilled",
        "hero_ability_skilled",
        "hero_ability_used",
        "me",
        "game",
        "match_state_changed",
        "clock_time_changed",
        "game_state",
    ],
    7764: [
        "gep_internal",
        "kill",
        "death",
        "assist",
        "headshot",
        "round_start",
        "match_start",
        "match_end",
        "team_round_win",
        "bomb_planted",
        "bomb_change",
        "reloading",
        "fired",
        "weapon_change",
        "weapon_acquired",
        "player_activity_change",
        "team_set",
        "info",
        "roster",
        "replay",
        "counters",
        "match_info",
        "mvp",
        "scoreboard",
        "kill_feed",
    ],
    8032: [
        "gep_internal",
        "game_info",
        "match_info",
        "counters",
        "mods",
    ],
    8954: [
        "gep_internal",
        "game_info",
        "match_info",
    ],
    9898: [
        "gep_internal",
        "collection",
        "scene_state",
        "decks",
        "match",
        "match_info",
        "arena",
    ],
    10624: [
        "gep_internal",
        "roster",
        "match_info",
        "kill",
        "death",
        "game_info",
        "me",
    ],
    10746: [
        "gep_internal",
        "game_info",
        "account_info",
        "match",
        "kill",
        "death",
        "match_info",
    ],
    10798: [
        "gep_internal",
        "stats",
        "teamGoal",
        "opposingTeamGoal",
        "match",
        "roster",
        "me",
        "match_info",
        "death",
        "game_info",
        "training",
    ],
    10826: [
        "gep_internal",
        "game_info",
        "match",
        "roster",
        "kill",
        "death",
        "match_info",
        "me",
        "defuser",
    ],
    10844: [
        "gep_internal",
        "match_info",
        "kill",
        "death",
        "assist",
        "game_info",
    ],
    10878: [
        "gep_internal",
        "matchinfo",
        "rosterinfo",
        "kills",
        "death",
        "RoundStart",
        "MatchEnd",
    ],
    10902: [
        "gep_internal",
        "summoner_info",
        "game_flow",
        "champ_select",
        "lobby_info",
        "end_game",
        "lcu_info",
        "game_info",
    ],
    10906: [
        "gep_internal",
        "kill",
        "match",
        "rank",
        "death",
        "location",
        "me",
        "team",
        "phase",
        "map",
        "roster",
        "revived",
        "killer",
        "counters",
        "match_info",
    ],
    21216: [
        "gep_internal",
        "items",
        "kill",
        "match_info",
        "rank",
        "me",
        "phase",
        "location",
        "team",
        "killed",
        "killer",
        "revived",
        "death",
        "counters",
        "match",
        "map",
    ],
    21308: [
        "gep_internal",
        "game_info",
        "match_info",
    ],
    21328: [
        "gep_internal",
        "game_info",
    ],
    21404: [
        "gep_internal",
        "game_info",
        "match_info",
        "player",
        "location",
        "match",
        "feed",
        "connection",
        "kill",
        "death",
        "portal",
    ],
    21566: [
        "gep_internal",
        "match_state",
        "kill",
        "death",
        "me",
        "team",
        "revive",
        "rank",
        "location",
        "roster",
        "match_summary",
        "kill_feed",
        "damage",
        "inventory",
        "match_info",
        "game_info",
        "localization",
    ],
    21570: [
        "gep_internal",
        "match_info",
        "me",
        "roster",
        "store",
        "board",
        "bench",
        "carousel",
        "live_client_data",
    ],
    21586: [
        "gep_internal",
    ],
    21620: [
        "gep_internal",
        "game_client_data",
        "match_info",
    ],
    21626: [
        "gep_internal",
        "match_info",
        "game_info",
        "kill",
        "death",
        "assist",
    ],
    21634: [
        "gep_internal",
        "match_info",
        "game_info",
    ],
    21640: [
        "gep_internal",
        "game_info",
        "me",
        "kill",
        "death",
        "match_info",
    ],
    21666: [
        "gep_internal",
        "match_info",
    ],
    21668: [
        "gep_internal",
        "game_info",
        "kill",
    ],
    21672: [
        "gep_internal",
        "me",
        "match_info",
    ],
    21816: [
        "gep_internal",
        "game_info",
    ],
    21848: [
        "gep_internal",
        "game_info",
        "match_info",
    ],
    21854: [
        "gep_internal",
        "match_info",
        "game_info",
        "kill",
        "death",
        "assist",
    ],
    21856: [
        "gep_internal",
        "match_info",
    ],
    21864: [
        "gep_internal",
        "game_info",
        "match_info",
        "location",
    ],
    21876: [
        "gep_internal",
        "match_info",
        "game_info",
        "me",
        "kill",
        "death",
    ],
    21960: [
        "gep_internal",
        "match_info",
        "game_info",
    ],
    22088: [
        "gep_internal",
        "game_info",
        "match_info",
    ],
    22312: [
        "gep_internal",
        "match_info",
        "game_info",
    ],
    22328: [
        "gep_internal",
        "match_info",
        "game_info",
    ],
    22638: [
        "gep_internal",
        "match_info",
        "location",
    ],
    22700: [
        "gep_internal",
        "match_info",
        "game_info",
        "location",
        "me",
    ],
    22730: [
        "gep_internal",
        "match_info",
        "live_data",
    ],
    22848: [
        "gep_internal",
    ],
    23222: [
        "gep_internal",
        "match_info",
        "location",
    ],
    23424: [
        "gep_internal",
    ],
    215701: [
        "gep_internal",
        "live_client_data",
        "carousel",
        "bench",
        "board",
        "store",
        "roster",
        "me",
        "match_info",
        "augments",
    ],
    223281: [
        "gep_internal",
        "match_info",
        "game_info",
    ],
}
